### ISSUE TITLE
how to add new language?

### ISSUE THREAD

**Issue by dakeshi** [bookchainio/steem-bluepaper#25]
Hi. I'd like to translate into korean but there are no korean in crowdin language list.
How to apply for a new language translation?

**Comment by testzcrypto** [comment]
Hello, I added Korean, more info about where to join you can read [here](https://steemit.com/utopian-io/@bookchain/steem-bluepaper-translation-task-request)

Please join Discord Utopian channel [here](https://discord.gg/VsyduEe)
